"""
Loads Snowfakery-generated CSVs into Salesforce via the Bulk API.

Expected input files (generated by sales_pipeline.yml):
  setup/salesforce/data/Account.csv
  setup/salesforce/data/Contact.csv
  setup/salesforce/data/Opportunity.csv

Usage:
    uv run python setup/salesforce/scripts/load_sales_pipeline.py
"""

import csv
import re
from pathlib import Path

from simple_salesforce.api import Salesforce

from sf_auth import get_salesforce_connection

DATA_DIR = Path(__file__).resolve().parent.parent / "data"

# Snowfakery internal IDs mapped by object to real Salesforce IDs.
id_map: dict[str, dict[str, str]] = {
    "Account": {},
    "Contact": {},
    "Opportunity": {},
}


def read_csv(path: Path) -> list[dict]:
    with open(path, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def resolve_references(records: list[dict]) -> list[dict]:
    """Replace Snowfakery reference IDs with real Salesforce IDs."""
    resolved = []
    for row in records:
        record = {}
        for key, value in row.items():
            if key == "id":
                continue  # Snowfakery internal ID, not a SF field
            if key in {"AccountId", "ParentId"} and value:
                record[key] = id_map["Account"].get(value, value)
            else:
                record[key] = value if value else None
        resolved.append(record)
    return resolved


def is_snowfakery_reference(value: str) -> bool:
    """Snowfakery references are usually numeric IDs or <Object>-<n> tokens."""
    if not value:
        return False
    return bool(re.match(r"^\d+$", value) or re.match(r"^[A-Za-z_]+-\d+$", value))


def can_resolve_record(record: dict) -> bool:
    """
    A record is ready when all *Id fields are either already resolved or
    not Snowfakery-generated reference tokens.
    """
    for key, value in record.items():
        if key == "id" or key not in {"AccountId", "ParentId"} or not value:
            continue
        if value in id_map["Account"]:
            continue
        if is_snowfakery_reference(value):
            return False
    return True


def bulk_insert(sf: Salesforce, sobject: str, records: list[dict], raw_ids: list[str]):
    results = getattr(sf.bulk, sobject).insert(records, batch_size=200)
    inserted = 0
    for raw_id, result in zip(raw_ids, results):
        if result["success"]:
            id_map[sobject][raw_id] = result["id"]
            inserted += 1
        else:
            print(f"  [warn] {sobject} {raw_id} failed: {result['errors']}")
    print(f"  {sobject}: {inserted}/{len(records)} inserted")


def load(sf: Salesforce, sobject: str):
    path = DATA_DIR / f"{sobject}.csv"
    if not path.exists():
        print(f"  [skip] {path} not found")
        return

    pending = read_csv(path)
    if not pending:
        print(f"  [skip] {path} is empty")
        return

    while pending:
        ready_rows = [row for row in pending if can_resolve_record(row)]
        if not ready_rows:
            # Best effort fallback to avoid infinite loops on bad data.
            print(f"  [warn] {sobject}: unresolved references remain; inserting as-is")
            ready_rows = pending

        raw_ids = [row["id"] for row in ready_rows]
        records = resolve_references(ready_rows)
        before_count = len(id_map[sobject])
        bulk_insert(sf, sobject, records, raw_ids)
        inserted_this_round = len(id_map[sobject]) - before_count

        processed_ids = set(raw_ids)
        pending = [row for row in pending if row["id"] not in processed_ids]
        if inserted_this_round == 0 and pending:
            print(f"  [warn] {sobject}: stopping early due to unresolved insert failures")
            break


def main():
    sf = get_salesforce_connection()

    # Order matters — Contacts and Opportunities reference Accounts
    for sobject in ["Account", "Contact", "Opportunity"]:
        print(f"Loading {sobject}...")
        load(sf, sobject)

    print("Done.")


if __name__ == "__main__":
    main()
