coordinator=true
node-scheduler.include-coordinator=true
http-server.authentication.type=PASSWORD
http-server.https.enabled=true
http-server.https.port=8443
http-server.https.keystore.path=/etc/trino/certs/trino.pem
internal-communication.shared-secret=${ENV:TRINO_SHARED_SECRET}
discovery.uri=http://localhost:8080
query.max-memory=1GB
query.max-memory-per-node=512MB
